const tags = (values) => values.map((value) => ({ value, label: value }));

export const jobTags = [
  { value: "EDUCATION", label: "EDUCATION" },
  ...tags([
    "10th Pass",
    "12th Pass",
    "ITI",
    "Diploma",
    "Undergraduate",
    "Graduate",
    "Post Graduate",
    "Professional Degree",
    "Any Qualification",
  ]),

  { value: "INDUSTRY", label: "JOB CATEGORIES" },
  ...tags([
    "Office Assistant",
    "Back Office",
    "Data Entry",
    "Computer Operator",
    "Receptionist",
    "Front Office Executive",
    "Office Administrator",
    "Documentation Executive",
    "Clerk",
    "Admin Executive",
    "Customer Support",
    "Telecaller",
    "Call Center",
    "BPO",
    "Customer Care Executive",
    "Voice Process",
    "Non-Voice Process",
    "Chat Support",
    "Sales Executive",
    "Field Sales",
    "Business Development",
    "Marketing Executive",
    "Retail Sales",
    "Insurance Sales",
    "Relationship Manager",
    "Telesales",
    "Promoter",
    "Store Executive",
    "Store Manager",
    "Cashier",
    "Billing Executive",
    "Retail Associate",
    "Inventory Executive",
    "Warehouse Executive",
    "Stock Manager",
    "Delivery Executive",
    "Delivery Partner",
    "Courier Executive",
    "Logistics Executive",
    "Warehouse Worker",
    "Picker/Packer",
    "Loading/Unloading",
    "Transport Executive",
    "Hotel Staff",
    "Housekeeping",
    "Waiter",
    "Chef/Cook",
    "Kitchen Helper",
    "Restaurant Manager",
    "Steward",
    "Hotel Management",
    "Nurse",
    "Nursing Assistant",
    "Medical Assistant",
    "Lab Technician",
    "Pharmacy Assistant",
    "Hospital Receptionist",
    "Caretaker",
    "Ward Assistant",
    "Hospital Support Staff",
    "Teacher",
    "Tutor",
    "Home Tutor",
    "Teaching Assistant",
    "School Staff",
    "Education Counselor",
    "Academic Counselor",
    "Preschool Teacher",
    "Banking Executive",
    "Relationship Executive",
    "Loan Executive",
    "Collection Executive",
    "Account Assistant",
    "Finance Executive",
    "Insurance Advisor",
    "Credit Executive",
    "Production Worker",
    "Machine Operator",
    "Quality Checker",
    "Production Supervisor",
    "Factory Helper",
    "Packaging Worker",
    "Assembly Worker",
    "Maintenance Worker",
    "Electrician",
    "Plumber",
    "Carpenter",
    "Mechanic",
    "Welder",
    "Fitter",
    "AC Technician",
    "Refrigeration Technician",
    "Mobile Repair Technician",
    "Painter",
    "Car Mechanic",
    "Bike Mechanic",
    "Service Advisor",
    "Automobile Technician",
    "Driver",
    "Car Washer",
    "Workshop Assistant",
    "Security Guard",
    "Security Supervisor",
    "CCTV Operator",
    "Security Officer",
    "Gatekeeper",
    "Housekeeper",
    "Cleaner",
    "Office Boy",
    "Helper",
    "Facility Executive",
    "Gardener",
    "Maintenance Staff",
    "Beautician",
    "Hairdresser",
    "Makeup Artist",
    "Salon Staff",
    "Spa Therapist",
    "Fitness Trainer",
    "Wellness Executive",
    "Tailor",
    "Fashion Assistant",
    "Garment Worker",
    "Cutting Master",
    "Embroidery Worker",
    "Boutique Assistant",
    "Fashion Sales",
    "Farm Worker",
    "Agriculture Assistant",
    "Dairy Worker",
    "Poultry Worker",
    "Farm Supervisor",
    "Nursery Worker",
    "Field Assistant",
    "Government Jobs",
    "Police",
    "Defence",
    "Railway",
    "Banking",
    "Postal Jobs",
    "SSC Jobs",
    "State Government Jobs",
    "PSU Jobs",
    "Municipal Jobs",
    "Property Sales Executive",
    "Real Estate Agent",
    "Property Manager",
    "Warehouse Associate",
    "Picker",
    "Packer",
    "Catalog Executive",
    "Seller Support",
    "Operations Executive",
    "Field Executive",
    "Field Officer",
    "Survey Executive",
    "Service Executive",
    "Collection Agent",
  ]),

  { value: "ROLE", label: "SPECIAL CATEGORIES" },
  ...tags([
    "10th Pass Jobs",
    "12th Pass Jobs",
    "Freshers Jobs",
    "No Experience Jobs",
    "Part-Time Jobs",
    "Work From Home",
    "Full-Time Jobs",
    "Internships",
    "Apprenticeships",
    "Jobs for Women",
    "Jobs for Students",
    "Night Shift Jobs",
    "Day Shift Jobs",
    "Jobs Near Me",
  ]),

  { value: "Job Type", label: "JOB TYPE" },
  ...tags([
    "Full Time",
    "Part Time",
    "Internship",
    "Apprenticeship",
    "Work From Home",
  ]),
];
